[mypy]
python_version = 3.12
explicit_package_bases = True
warn_unused_configs = True

# ignore untyped third-party libs
[mypy-pgvector.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-PyPDF2.*]
ignore_missing_imports = True

[mypy-docx.*]
ignore_missing_imports = True

[mypy-langchain_openai.*]
ignore_missing_imports = True
